---
title: "R ile Veri Analizi Atölyesi"
site: distill::distill_website
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 5
editor_options: 
  markdown: 
    wrap: 72
---

# Ders İçeriği

Ders Kaynağı: <https://r4ds.had.co.nz/>

## 1.Hafta

### [Programlamaya Giriş ve R](https://resolved-team.github.io/RileVeriAnalizi/posts/welcome/)

**11 Mayıs Çarşamba : 20.00-22.00**

-   Programlama dilleri ve mantığı

-   Arayüz vs. Kod

-   Neden R

-   R vs. Python

-   Rstudio kullanımı

-   Rmarkdown

-   Kütüphane kullanımı

-   Kaggle tanıtımı

    **Ödev:**

-   *Kurulumların kişisel bilgisayarlarda tamamlanması*

-   *Kaggle'dan ya da farklı kaynaklardan ders boyu kullanılacak verinin
    seçilip onaylatılması*

### [Veri Yapıları ve Döngüler](https://resolved-team.github.io/RileVeriAnalizi/posts/2022-05-14-ikinciders/)

**14 Mayıs Cumartesi: 14.00-16.00**

-   Veri yapıları

-   Değişken ve opertörler

-   Vektör, Liste ve DataFrame

-   Veri alt kümelerine ulaşım

-   %\>%

-   Veri okuma ve yazma

    **Ödev:**

-   *Kendi veriniz üzerinden derste gösterilen fonsksiyonların
    uygulaması*

### Dplyr Paketi ve Döngüler

**15 Mayıs Pazar : 14.00-16.00**

-   For döngüsü

-   While döngüsü

-   Fonksiyonlar

-   select fonksiyonu

-   filter fonksiyonu

-   arange fonksiyonu

    **Ödev:**

-   *Kendi veriniz üzerinden derste gösterilen fonsksiyonların
    uygulaması*

## 2. Hafta

### Dplyr Paketi ile Veri Temizliği

**18 Mayıs Çarşamba : 19.00-21.00**

-   mutate fonksiyonu

-   summarize fonksiyonu

-   count fonksiyonu

-   case_when fonksiyonu

-   pivot_longer fonksiyonu

-   pivot_wider fonksiyonu

    **Ödev:**

-   *Kendi veriniz üzerinden derste gösterilen fonsksiyonların
    uygulaması*

### Ggplot Paketi ile Görselleştirme

**20 Mayıs Cuma : 19.00-21.00**

-   Grafik grameri

-   Veri tipi görselleştirme ilişkisi

-   Çeşitli görselleştirme türleri

-   Grafik özelleştirme

**Ödev**

-   *Kendi veriniz üzerinden 2 farklı görselleştirme* yapılması

### Tarih, saat ve mekan verisi

**21 Mayıs Cumartesi : 14.00-17.00**

-   Lubridate paketi

-   Leaflet paketi

**Ödev**

-   *Kendi verinizi kullanarak paketlerden en az birini kullanarak bir
    analiz ya da görselleştirme yapılması*

### Regex ve StringR Paketi ile Metin İşleme

**22 Mayıs Pazar : 14.00-17.00**

-   Regex

-   StringR ile metin işleme

-   Temel metin analizi fonsksiyonları

**Ödev**

-   *Kendi verinizi kullanarak paketlerden en az birini kullanarak bir
    analiz yapılması*

**Bitirme Ödevi**

Seçilen veri üzerinden bir araştırma sorusu ile kısa bir blog yazısının
yazılması
